camera_speed: 5
space_size: [700, 500]
stars: # Required
    avg_groups: 10
    groups_sigma: 3
    avg_group_size: 10
    group_size_sigma: 3
    position_sigma: 50
sim: # Required
    time: # Required
        start: 0
        increment: 1
