camera_speed: 1
space_size: [1400, 1000]
screen_size: [700, 500]
stars: # Required
    avg_groups: 10
    groups_sigma: 3
    avg_group_size: 10
    group_size_sigma: 3
    position_sigma: 50
nebulas: # Required
    avg_nebula_centers: 10
    centers_sigma: 5
    cloud_dispersion: 100
    avg_center_radius: 10
    center_radius_sigma: 5
    avg_nebulas: 1
    sigma_nebulas: 0.2
sim: # Required
    time: # Required
        start: 0
        increment: 1
